### ISSUE TITLE
Symbols2: incorrect FFF9–FFFB

### ISSUE THREAD

**Issue by DLasher106** [notofonts/symbols#10]
NotoSansSymbols2-Regular.ttf has incorrect glyphs for FFF9, FFFA, and FFFB, the Interlinear Annotation marks. They should have **I**AA, **I**AS, and **I**AT, but Symbols2 has **1**AA, **1**AS, and **1**AT.

**Comment by SKing-2003** [comment]
This issue appears resolved.
