### ISSUE TITLE
Self-intersecting glyphs with U+20E0

### ISSUE THREAD

**Issue by dscorbett** [notofonts/symbols#13]
### Font
NotoSansSymbols-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols-unhinted.zip
Date: 2018-03-24

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
Many glyphs with U+20E0 self-intersect.

### Character data
R⃠
U+0052 LATIN CAPITAL LETTER R
U+20E0 COMBINING ENCLOSING CIRCLE BACKSLASH

### Screenshot
![R⃠](https://user-images.githubusercontent.com/1124347/38737521-886e0808-3efd-11e8-9675-3f3892b1584a.png)

**Comment by simoncozens** [comment]
I suspect we have fixed this in the toolchain; here's Safari:

<img width="268" alt="Screenshot 2023-01-27 at 08 58 00" src="https://user-images.githubusercontent.com/106728/215047150-681a5557-41c9-498c-8fba-d15c77475283.png">

and Chrome:

<img width="391" alt="Screenshot 2023-01-27 at 08 58 13" src="https://user-images.githubusercontent.com/106728/215047193-39653bb1-ce58-4259-b70c-dfe5033e40d3.png">
