### ISSUE TITLE
missing symbols from code page 437 : box drawing and filled boxes characters in Unicode (U+2500..U+25A0)

### ISSUE THREAD

**Issue by verdy-p** [notofonts/symbols#19]
Is there a way to add the missing symbols used in DOS code page 437 (filled boxes, and box drawing characters) ?

These are the characters in code range 0xB0 to 0xDF in that codepage (with their description in French), and they are all in the same Unicode range (U+2500 to U+257F: box drawing characters, and U+2580 to U+259F: filled boxes); some of them are mapped like this in CP437:
* 0xB0: U+2591 boîte grisée à vingt-cinq pourcents
* 0xB1: U+2592 boîte grisée à cinquante pourcents
* 0xB2: U+2593 boîte grisée à soixante-quinze pourcents
* 0xB3: U+2502 tracé de boîte simple vertical
* 0xB4: U+2524 tracé de boîte simple vertical et à gauche
* 0xB5: U+2561 tracé de boîte simple vertical et double vers la gauche
* 0xB6: U+2562 tracé de boîte double vertical et simple vers la gauche
* 0xB7: U+2556 tracé de boîte simple à gauche et double vers le bas
* 0xB8: U+2555 tracé de boîte double à gauche et simple vers le bas
* 0xB9: U+2563 tracé de boîte double vertical et vers la gauche
* 0xBA: U+2551 tracé de boîte double vertical
* 0xBB: U+2557 tracé de boîte double vers la gauche et vers le bas
* 0xBC: U+255D tracé de boîte double vers la gauche et vers le haut
* 0xBD: U+255C tracé de boîte simple vers la gauche et double vers le haut
* 0xBE: U+255B tracé de boîte double vers la gauche et simple vers le haut
* 0xBF: U+2510 tracé de boîte simple vers la gauche et le bas
* 0xC0: U+2514 tracé de boîte simple vers la droite et vers le haut
* 0xC1: U+2534 tracé de boîte simple horizontal et vers le haut
* 0xC2: U+252C tracé de boîte simple horizontal et vers le bas
* 0xC3: U+251C tracé de boîte simple vertical et vers la droite
* 0xC4: U+2500 tracé de boîte simple horizontal
* 0xC5: U+253C tracé de boîte simple horizontal et vertical
* 0xC6: U+255E tracé de boîte simple vertical et double vers la droite
* 0xC7: U+255F tracé de boîte double vertical et simple vers la droite
* 0xC8: U+255A tracé de boîte double vers la droite et vers le haut
* 0xC9: U+2554 tracé de boîte double vers la droite et vers le bas
* 0xCA: U+2569 tracé de boîte double horizontal et vers le haut
* 0xCB: U+2566 tracé de boîte double horizontal et vers le bas
* 0xCC: U+2560 tracé de boîte double vertical et vers la droite
* 0xCD: U+2550 tracé de boîte double horizontal
* 0xCE: U+256C tracé de boîte double horizontal et vertical
* 0xCF: U+2567 tracé de boîte double horizontal et simple vers le haut
* 0xD0: U+2568 tracé de boîte simple horizontal et double vers le haut
* 0xD1: U+2564 tracé de boîte double horizontal et simple vers le bas
* 0xD2: U+2565 tracé de boîte simple horizontal et double vers le bas
* 0xD3: U+2559 tracé de boîte simple vers la droite et double vers le haut
* 0xD4: U+2558 trait de boîte double vers la droite et simple vers le haut
* 0xD5: U+2552 trait de boîte double vers la droite et simple vers le bas
* 0xD6: U+2553 trait de boîte simple vers la droite et double vers le bas
* 0xD7: U+256B trait de boîte simple horizontal et double vertical
* 0xD8: U+256A trait de boîte double horizontal et simple vertical
* 0xD9: U+2518 trait de boîte simple vers la gauche et vers le haut
* 0xDA: U+250C trait de boîte simple vers la droite et vers le bas
* 0xDB: U+2588 boîte pleine
* 0xDC: U+2584 boîte demi-pleine en bas
* 0xDD: U+258C boîte demi-pleine à gauche
* 0xDE: U+2590 boîte demi-pleine à droite
* 0xDF: U+2580 boîte demi-pleine en haut

There's also one character in CP437 which maps to a symbol in the next Unicode block for geometric forms: ■ (U+25A0), mapped at 0xFE in CP437.

For now they cannot be displayed at all with any Noto font. Only a few symbols for the Unicode block starting at U+25A0 are mapped in "Noto Sans Math", some others are defined in "Noto Sans Emoji", but there's no consistency for this block of geometric shapes.

When rendering legacy texts using CP437 codepages (or other DOS codepages) we frequently get tofu, and when using Noto fonts with monospaced styles (including CJK fonts), they are not properly aligned.

With non-monospaced fonts, all these characters should have the same metric as the non-breaking space (also mapped in CP437 at 0xFF), or as the ideographic space (in CJK fonts).

I think they should be defined in "Noto Sans Symbols" or "Noto Sans Symbols2".
This does not require complex glyphs.

**Comment by simoncozens** [comment]
Closing in favour of consolidated report #69.
