### ISSUE TITLE
Wrong glyphs for WHITE/BLACK CHESS PAWN ROTATED TWO HUNDRED SEVENTY DEGREES

### ISSUE THREAD

**Issue by dscorbett** [notofonts/symbols#20]
### Font
NotoSansSymbols2-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/phaseIII_only/unhinted/otf/NotoSansSymbols2/NotoSansSymbols2-Regular.otf
Date: 2020-04-09

### Font version
Version 2.002

### Issue
The glyphs of U+1FA38 and U+1FA3E should be rotated 270° clockwise.

### Character data
🨸🨾
U+1FA38 WHITE CHESS PAWN ROTATED TWO HUNDRED SEVENTY DEGREES
U+1FA3E BLACK CHESS PAWN ROTATED TWO HUNDRED SEVENTY DEGREES

### Screenshot
![🨸🨾](https://user-images.githubusercontent.com/1124347/78900056-4ad41800-7a44-11ea-9046-96477e8a179f.png)

**Comment by Mercury13** [comment]
Still the pawn is there :(

**Comment by simoncozens** [comment]
Yep, bugs don't get fixed just through the passage of time; someone has to fix it. (I fixed it.)
