### ISSUE TITLE
Questionable hatching for large orange shapes

### ISSUE THREAD

**Issue by dscorbett** [notofonts/symbols#22]
### Font
NotoSansSymbols2-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/fcf8d5d5568fc96efcc4cbe6f9fbd402f62de98a/phaseIII_only/unhinted/otf/NotoSansSymbols2/NotoSansSymbols2-Regular.otf
Date: 2020-05-03

### Font version
Version 2.002

### Issue
The monochromatic glyphs in this font for the large colored shapes U+1F7E0..U+1F7EB use the same heraldic hatchings as the glyphs in the Unicode code chart, except for U+1F7E0 and U+1F7E7. In the code chart, they use crossed horizontal lines and diagonally rising lines. In this font, they use crossed horizontal lines and vertical lines, which usually represents sable, i.e. black. Although there is no requirement to match the convention used by Unicode, the fact that the other shapes do match implies that this hatching for orange may not have been intentional.

### Character data
🟠🟧
U+1F7E0 LARGE ORANGE CIRCLE
U+1F7E7 LARGE ORANGE SQUARE

### Screenshot
![🟠🟧](https://user-images.githubusercontent.com/1124347/80925519-61794080-8d5e-11ea-83cb-1a17b647e8ed.png)

**Comment by simoncozens** [comment]
These two glyphs are now more heraldically tenné:

![shape](https://user-images.githubusercontent.com/106728/215060088-2f3737bb-17d2-4570-a92b-d5dcd4695b8d.png)
