### ISSUE TITLE
Merge NotoSansSymbols and NotoSansSymbols2

### ISSUE THREAD

**Issue by ghost** [notofonts/symbols#27]
Can you merge NotoSansSymbols and NotoSansSymbols2? They cover different parts of the same block (Miscellanous Symbols). If you use BabelPad you can only cover part of that block, as BabelPad can use only one font for each Unicode block.

**Comment by simoncozens** [comment]
I think it's unlikely that we're going to do this, and certainly not in the next few years; it's a massive amount of drawing for quite a small gain. Maybe easier to fix Babelpad? ;-)
