### ISSUE TITLE
Mahjong Tile Designs - Circle Suite

### ISSUE THREAD

**Issue by tjablin** [notofonts/symbols#3]
### Title 
  > Mahjong Tile Designs - Circle Suite

### Font 
  > NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Pre-installed

### Font Version
2.003

### OS name and version
Debian GNU/Linux rodete

### Application name and version
  > If the issue is observed using a specific app.

### Issue

The design of the circle suite in the Mahjong Tile Unicode Block looks weird in Noto Sans Symbols 2.

Currently, the sizes of the circles for the four, five, six, seven, and eight of dots are non-uniform. Typically, these circles are the same size and only one, two, and three have larger circles.

Currently, the six of circles features six equally spaced circles in a rectangular two by three layout. Typically, the bottom four circles on the six of circle are arranged in a tight square and the top two circles are offset by a large gap. Without the gap between the two dot and bottom four circles, I think it is difficult to rapidly distinguish the six and eight of circles, particularly at small font sizes. The six of circles typically looks like the eight of circles with the second row of circles deleted.

Currently, the seven of circles has four circles in a tight rectangle on the bottom and three circles at a thirty degree angle on top. Typically, the bottom four circles should be arranged in a square identical to the six of circles. The seven of circles typically looks like the eight of circles with the top four circles replaced with three circles on a diagonal.

Currently, the eight of circles has two columns of four circles separated by a gap. Typically, these two columns touch.

Currently, the nine of circles has narrow gaps between each row of circles. Typically, the top and bottom row of the nine of circles aligns of the top and bottom row of the eight of circles.

Photo of a Typical Mahjong Sets
![Photo from Wikipedia](https://upload.wikimedia.org/wikipedia/commons/1/12/MJTiles_Fullset.png)

### Character data
🀙🀚🀛🀜🀝🀞🀟🀠🀡

U+1F01A - U1F021

### Screenshot
![Screenshot from 2022-05-11 14-35-38](https://user-images.githubusercontent.com/4314234/167951916-991c5d30-be7c-4dd3-baa8-eaf59a66b228.png)

**Comment by simoncozens** [comment]
Here is the new design:

<img width="736" alt="Screenshot 2023-01-27 at 09 33 05" src="https://user-images.githubusercontent.com/106728/215053960-f526d5cb-2300-4515-b8ac-8d7efbe3c73b.png">

**Comment by tjablin** [comment]
Thanks for the new design! I think they are much improved versus the old glyphs. Would you consider aligning the top and bottom row of the nine of circles with the top and bottom row of the eight of circles?

**Comment by ChiefMikeK** [comment]
## How about a survey/vote ↑👍 👎↓
![NineDotTile(modified)](https://user-images.githubusercontent.com/20070053/221361609-3d24bd50-a0d6-4573-8fd3-6bacdcdf4eaa.png)
