### ISSUE TITLE
Reversed rotated fleuron is larger than other two

### ISSUE THREAD

**Issue by john-cj** [notofonts/symbols#31]
The word "Test" is set in Noto Serif 12 pt. The fleurons are set in Noto Sans Symbols 2. The software is InDesign CS6.

![image](https://user-images.githubusercontent.com/18004961/153734763-42a88566-03c2-4f45-a7d0-b340f90f53ce.png)

```
Test ❦ ❧ ☙
```

As you can see, the third fleuron on the image is significantly larger than the first two.

**Comment by simoncozens** [comment]
I have made U+2767 and U+2619 rotations of the U+2766 floral heart glyph.

![shape](https://user-images.githubusercontent.com/106728/215061589-4c67062f-8cfd-43d2-8827-c4aa5a288be7.png)
