### ISSUE TITLE
Language-neutral tofu of Windows 10 + Unicode 13

### ISSUE THREAD

**Issue by Mercury13** [notofonts/symbols#32]
All six Creative Commons chars: U+1F10D…1F10F, 1F16D…1F16F
U+1F12F Copyleft symbol
U+1F1AD Mask work symbol
U+1F23B Squared CJK unified ideograph-914D
U+1F260 Rounded symbol for fu …………… U+1F265 Rounded symbol for cai
U+1F900 Circled cross formee with four dots  …………… U+1F90C Pinched fingers
U+1F972 Smiling face with tear
U+1F977 Ninja
U+1F978 Disguised face
U+1F9AB Beaver
U+1F9AC Bison
U+1F9AD Seal
U+1FA38 White chess pawn rotated two hundred seventy degrees (not tofu, but wrong glyph)
U+1FA3E Black chess pawn rotated two hundred seventy degrees (same)

**Comment by simoncozens** [comment]
Some of these:

> U+1F972 Smiling face with tear
> U+1F977 Ninja
> U+1F978 Disguised face
> U+1F9AB Beaver
> U+1F9AC Bison
> U+1F9AD Seal

are out of scope for Symbols as they do not have text presentation.

> U+1FA38 White chess pawn rotated two hundred seventy degrees (not tofu, but wrong glyph)
> U+1FA3E Black chess pawn rotated two hundred seventy degrees (same)

This is a separate issue, now fixed.

**Comment by simoncozens** [comment]
> U+1F900 Circled cross formee with four dots …………… U+1F90C Pinched fingers

These (at least up to 1F90B) are typicon symbols and should go in LGC, see https://github.com/notofonts/latin-greek-cyrillic/issues/58.

That leaves

* U+1F10D-1F10F, 1F16D-1F16F
* U+1F12F
* U+1F1AD
* U+1F23B
* U+1F260-1F265
* U+1F900-1F90C

which I shall add to my consolidated list of missing glyphs.
