### ISSUE TITLE
Add U+23FB - U+23FE to Noto Sans Symbols (Unicode 9 power symbols)

### ISSUE THREAD

**Issue by edent** [notofonts/symbols#45]
Unicode 9 contains some additions to the [Miscellaneous Technical block](http://www.unicode.org/Public/9.0.0/charts/blocks/U2300.pdf)

These are 

```
Power        &#x23FB;   ⏻
Toggle Power &#x23FC;   ⏼
Power On     &#x23FD;   ⏽
Power Off    &#x2B58;   ⭘
Sleep Mode   &#x23FE;   ⏾
```

Please can these be added to Noto Sans Symbols.

Free reference fonts can be found at http://unicodepowersymbol.com/font/ or https://github.com/jloughry/Unicode 

(I'm [one of the proposers of the symbols](http://www.unicode.org/L2/L2014/14009r-power-symbol.pdf))

**Comment by edent** [comment]
10 years after opening this issue and the Android team still haven't updated their font stack to use most of the modern Noto fonts.

https://issuetracker.google.com/issues/366415133

**Comment by simoncozens** [comment]
I've been pushing for some time to have the Noto fonts updated in Android, particularly as there are fixes to minority language support that need to happen. There are, unfortunately, good reasons why it hasn't happened yet. Android has very strict processes around quality control, and especially around anything which adds to the file size of the installed system image, and so updating the fonts takes time and manpower - and that means that it needs to be made a priority, and thus far the Android Text team (which is surprisingly small!) have just had other things that needed to happen first. I'm slightly more hopeful now that we have someone understands the importance and who is able to liaise with the Android team more to try to make it happen. We'll see. (Disclaimer: I'm a contractor helping to improve the Noto library, not a Googler, so my sway is limited; and obviously, I'm not speaking for Google in any way.)

**Comment by edent** [comment]
Thanks for the update. It's just rather galling to see [Google update 4,000 new emoji](https://blog.google/products-and-platforms/platforms/android/world-emoji-day-noto-3d/) which will almost certainly increase the system image size more than an update to the latest Noto fonts.

I appreciate that you're not a Googler. But if you could pass this annoyance on to someone who is, I would appreciate it.
