### ISSUE TITLE
Noto Symbols needs variation sequence slashed zero form of empty set

### ISSUE THREAD

**Issue by roozbehp** [notofonts/symbols#6]
UTC partially accepted the proposal http://www.unicode.org/L2/L2015/15268-slashed-zero.pdf, and fast-tracked it for Unicode 9. The following variation sequence was added:

`<U+2205, U+FE00>`

The variant form (for a slash-zero style empty set) needs to be added to Noto Sans Symbols.

**Comment by simoncozens** [comment]
This is no longer in the symbols font; I'll add an issue in the math font (which is currently being redesigned), and in Noto Sans.
