### ISSUE TITLE
Unicode 15 Addition of U+1F7D9 NINE POINTED WHITE STAR

### ISSUE THREAD

**Issue by LaPingvino** [notofonts/symbols#64]
Unicode 15 released today and I suspect the new symbol NINE POINTED WHITE STAR would belong in one of the Symbols Noto fonts to have fallback support.

So if there is any need to request the addition of the character, here it is, (otherwise it's basically a tracking issue for when it will be added).

**Comment by LaPingvino** [comment]
@roozbehp I saw you comment on another Noto Github case, maybe you know what the correct procedure here is or if I should just be patient?

**Comment by simoncozens** [comment]
Thanks for the bug report. We automatically keep track of which codepoints are covered by Noto and which aren't, and I'm hoping we'll be able to commission some new drawings (or receive them as community contributions - please feel free!) soon.

**Comment by LaPingvino** [comment]
what format should community contributions be in?

**Comment by LaPingvino** [comment]
Ah I found out you use .glif files, sorry for my ignorance. FontForge can output those perfectly, so here is a link to the version I created for my test font: https://gist.github.com/LaPingvino/d7c28c12cd7445cde5bbf2c5568ae1a1
As said, it's based on a Public Domain SVG file and with its simplicity I won't even really be able to claim copyright over it either.

**Comment by simoncozens** [comment]
Thanks for this; I will take a look. But (without having looked at it) any contribution would need to fit with the rest of the font in terms of stroke width, style, etc., so I am a little bit reticent about grabbing things from external sources.

**Comment by LaPingvino** [comment]
I fully agree about that, but seeing my experience from testing this with Georgia before, I'm not all too worried. If you see anything specific that doesn't fit well, I can probably adjust from here. I already adjusted it for font usage, it's not a straight 1 to 1 copy.

**Comment by LaPingvino** [comment]
@simoncozens did you find time to give it a look? (I gave it one revision to fit correctly xD)

**Comment by LaPingvino** [comment]
@simoncozens I gave figuring out the source format some time and it looks like this should do it. Other than probably some style considerations re: the lib.plist file I think this should work?

**Comment by Mercury13** [comment]
Have five plutoids in my Unicodia. Drawn by me, but Quaoar‘s corners are rounded for simplicity.
The rules are simple: everything drawn by me may be used what the funk you want to.

**Comment by Mercury13** [comment]
And maybe I’ll draw Nag alphabet.

**Comment by Mercury13** [comment]
> And maybe I’ll draw Nag alphabet.

Already have a draft, need lots of time to track, kern and lay marks.

**Comment by LaPingvino** [comment]
@Mercury13 how is it getting along?

**Comment by Mercury13** [comment]
@LaPingvino Implemented somehow, but because of lack of knowledge there are as many as six RLIGs.

**Comment by Mercury13** [comment]
@LaPingvino Here’s the screenshot
![image](https://user-images.githubusercontent.com/10164882/198710421-cf4afb47-441b-4068-b225-136b3ff00dbd.png)

**Comment by Mercury13** [comment]
The exact list of RLIGs: IC+prime, Theta+prime, Acurl+prime, 8bar+prime, 3curl+prime, openO+prime
Why: prime is a spacing character, and if it’s kerned too close, I make RLIG.

**Comment by Mercury13** [comment]
And here are other U15 characters
![image](https://user-images.githubusercontent.com/10164882/198713570-040b53a8-d8aa-42e2-bd69-174727f238d6.png)
![image](https://user-images.githubusercontent.com/10164882/198713678-9b99fe95-c984-4dc2-ab56-e2e5b76fb9d3.png)
![image](https://user-images.githubusercontent.com/10164882/198713721-f6c83599-78d7-48ea-931b-48f82c426d03.png)
![image](https://user-images.githubusercontent.com/10164882/198713862-80ced85f-2455-46d2-b287-5f9772ae2ec7.png)
I made Cyrillic superscripts/subscripts from bolder letters, it looks nicer.

**Comment by LaPingvino** [comment]
@Mercury13 hope you are safe and everything, just realized you are from Kyiv. How are the plans for finishing and release/submitting? Greetings from Portugal.

**Comment by Mercury13** [comment]
Yes, I’m from Kyiv. IDK how to release, especially for variable fonts. Everything is in Unicodia’s FunkySample font.

**Comment by LaPingvino** [comment]
@simoncozens any way to help @Mercury13 out here? or any other processes going on about this?

**Comment by eliheuer** [comment]
@simoncozens I would like to help move this forward if possible. I'm a Baha'i with a deep interest in Baha'i publishing/design and can review/clean-up the drawing( U+1F7D9 NINE POINTED WHITE STAR) and PR a new Glyphs file with the packager. I also know and have already been communicating with [LaPingvino](https://github.com/LaPingvino) about this issue.

**Comment by ctrlcctrlv** [comment]
it's just a star with nine points, there are plenty of stars in the font, i was asked by @LaPingvino to get this unstuck in discord so this is my attempt, there's a lot of talking about a glyph so how about somebody just draws one that fits w/the others…

**Comment by eliheuer** [comment]
I dropped the ball on this due to a new baby, sorry. I will look at this again today/this weekend. 

I collect rare Baha'i books so I have a lot of thoughts on how it should be drawn and want to do a good job.

I also make 9-pointed star art with python.

![7973b21a06bacea231341b3a81f6aaa5](https://github.com/notofonts/symbols/assets/5162664/aba6cc1c-278f-4b03-9235-589bf3e0bcbe)

**Comment by simoncozens** [comment]
That's an awesome board game waiting to happen.

**Comment by ctrlcctrlv** [comment]
ok @eliheuer all i am saying is it seems that perhaps Baha’i users (or at least one Baha’i user) would prefer an acceptable star to no star. beautiful star though(!!!), ngl. if your time has a lot of demands on it perhaps you and @LaPingvino discuss possibly merging an acceptable star and then later you come with the perfect star. just trying to do my part to get it unstuck :o)

**Comment by LaPingvino** [comment]
Fully agree with @ctrlcctrlv

**Comment by ctrlcctrlv** [comment]
thanks, and i do not mean to detract from the religious significance of this particular star by saying it's “just” a nine-pointed star. no symbol is just a symbol, i was not speaking in the philosophical sense obviously. only in the font engineering / type design sense, that it is a regular compound star polygon of order {9/3} (also known as an ennagram). we know how to draw this, we have the technology. people can apply the meaning they wish to the geometry. :-)

**Comment by LaPingvino** [comment]
Especially as this is for Noto Sans, which is a fallback font and should work for most if not all possible purposes. We can make nicer fonts later.

**Comment by ctrlcctrlv** [comment]
perhaps it's that we've a `wght` running from 100 to 900?

![image](https://github.com/notofonts/symbols/assets/838783/33ea6870-e0ca-4757-a320-0cabf8d312f5)

there's no hinting leading to failure cases in the pentagram such as:

![image](https://github.com/notofonts/symbols/assets/838783/d7900cc7-def2-4874-97da-bd0da39f201b)

**Comment by LaPingvino** [comment]
I reopened #66 and put it in the right directory for glyphsapp that is used now. The only thing missing then is making sure it integrates correctly, which I cannot check because glyphsapp is not open source as explained by @ctrlcctrlv

**Comment by LaPingvino** [comment]
> what was wrong with #66?

I think nothing but the need for @simoncozens to verify with a skilled font maker that it is actually okay.
