### ISSUE TITLE
“Full” version of Symbols2 — weight of Latin characters

### ISSUE THREAD

**Issue by DLasher106** [notofonts/symbols#65]
The “full” versions of the Noto fonts have Latin letters with appropriate weight, defaulting to regular (400).

Except that for the Noto Sans Symbols2 font (https://notofonts.github.io/fonts/NotoSansSymbols2/full/ttf/NotoSansSymbols2-Regular.ttf) has thin weight Latin letters. I believe they should be regular weight, or possibly a heavier weight to better match the character **2**.

In this screenshot, all of the Noto fonts are full versions:
![Symbols2](https://user-images.githubusercontent.com/18547206/192912361-e1c403da-5a94-4c67-b891-776eac1da327.png)

**Comment by simoncozens** [comment]
Oh, nice catch. Perhaps Symbols 2 describes its own weight incorrectly, so it is being matched with a lighter Latin than it really is.

**Comment by simoncozens** [comment]
This is fixed!
