### ISSUE TITLE
Enlarge symbols: Phaistos Disc, domino, cards, mahjong

### ISSUE THREAD

**Issue by Mercury13** [notofonts/symbols#68]
### Title
Enlarge symbols: Phaistos Disc, domino, cards, mahjong

### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: this repo
Date: 2023-01-20

### Font Version
2.005

### OS name and version
All OS

### Application name and version
All apps

### Issue
  1. Draw any of these symbols
  2. Too small
  3. Want larger

### Character data
U+101D0 Phaistos Disc sign Pedestrian
………
U+101FD Phaistos Disc sign Combining oblique stroke

U+1F000 mahjong tile East wind
………
U+1F0F5 playing card Trump-21

### Screenshot
Noto card (w=676)
![image](https://user-images.githubusercontent.com/10164882/213640553-3979f2bf-0301-4c82-862b-2ac9f42d7ce3.png)

Noto emoji (w=1008)
![image](https://user-images.githubusercontent.com/10164882/213640599-394ad4d5-efdc-4d33-9cc5-e5017810ccb2.png)

Same with DejaVu
![image](https://user-images.githubusercontent.com/10164882/213640836-6a28ce6d-ee34-4342-91b1-2140f246caa8.png)

Same with Segoe
![image](https://user-images.githubusercontent.com/10164882/213640960-b842e934-698e-41fc-bec6-4535ae87c802.png)

**Comment by simoncozens** [comment]
This probably won't be something we do. Within a block, the sizes of glyphs are consistent. If you want to display the phaistos disc man playing mahjongg, the glyphs will have different sizes, but that's a very specialised use case.

**Comment by Mercury13** [comment]
Sorry, they are not consistent to font’s upper/lower bounds — it leaves too much space above/below line. These characters are way smaller than even emoji.
Of course, my Unicodia is a culprit, and it never shows Phaistos Disc men playing mahjongg. It shows symbols one by one, and even a single character makes such things.
![image](https://user-images.githubusercontent.com/10164882/213677038-fc9f2597-fb0f-4b51-8793-44885719bb5f.png)

**Comment by Mercury13** [comment]
In Qt or HTML it’s possible to fix somehow using CSS, but e.g. in word processor — just accept.

**Comment by Mercury13** [comment]
This is just normal practice: to be readable, such pictures must occupy almost entire line. And if I enlarge them to be readable, and it pushes line outwards. I don’t mean then consistent to font’s upper lower bounds. I want them to be readable together with normal text without strange CSS hacks.
