### ISSUE TITLE
NotoSansSymbols-Regular is not monospaced

### ISSUE THREAD

**Issue by hyc** [notofonts/symbols#7]
On Android up to KitKat, DroidSansFallback.ttf supplied Box Drawing characters and various other graphic characters. These were aligned with DroidSansMono. On Android Lollipop and Marshmallow the Box Drawing characters and other graphics ranges have been removed from DroidSansFallback and NotoSansSymbols-Regular has been used instead. However, since NotoSansSymbols-Regular is not monospaced, monospaced displays using these graphics characters are completely jumbled and misaligned.

First noted here http://stackoverflow.com/questions/33226826/nexus-5-monospace-font-has-different-width-for-unicode-circles

The Box Drawing characters are quite broken now, because of the leading in their definitions they don't actually connect to draw complete boxes, there are major gaps and misalignments between each component.

**Comment by SKing-2003** [comment]
This is no longer a bug, as Noto Sans Mono exists for such uses.

**Comment by hyc** [comment]
Nice to know. Any chance of providing an apk that can install these fonts on older Android versions?

**Comment by simoncozens** [comment]
> Any chance of providing an apk that can install these fonts on older Android versions?

I wouldn't know how to do that, to be honest - there doesn't seem to be an easy way to install fonts on Android, as far as I can Google. Third-party distributions of Noto fonts are... well, a third-party thing. If someone knows how to package these fonts as an Android-installable APK, then please feel free.

> This is no longer a bug, as Noto Sans Mono exists for such uses.

Indeed; closing.
