### ISSUE TITLE
U+2139 in Noto Symbols should have serifs.

### ISSUE THREAD

**Issue by roozbehp** [notofonts/symbols#8]
U+2139 INFORMATION SOURCE is a well-established sign that appears in airports etc. It always seems to have serifs (see for example https://www.cg.tuwien.ac.at/eurovis2012/images/venue/airport-directions.png and http://thumbs.dreamstime.com/z/information-sign-1259538.jpg).

But the version included in Noto Symbols does not have serifs. It should.

**Comment by SKing-2003** [comment]
U+2139 is not currently in either of the Noto Symbols fonts.

**Comment by simoncozens** [comment]
Yes; this has moved to LGC (and has serifs).
