### ISSUE TITLE
U+1D377 "𝍷" TALLY MARK ONE is spaced improperly

### ISSUE THREAD

**Issue by chris-morgan** [notofonts/symbols#81]
**Font:** NotoSansSymbols2-Regular.ttf
**Version:** v2.008
**Source:** Arch Linux *noto-fonts* package, version 1:23.11.1-1

Tally marks are encoded in Unicode with two characters:

- U+1D377 "𝍷" TALLY MARK ONE, and
- U+1D378 "𝍸" TALLY MARK FIVE.

Tally marks for two, three and four are intended to be composed of sequences of TALLY MARK ONE. (I don’t actually have a good source for this claim, but earlier versions of the proposal contained code points for TWO, THREE and FOUR; evidently the author was told to cut them out as unnecessary. <https://en.wikipedia.org/wiki/Counting_Rod_Numerals_(Unicode_block)#History> has a list of the relevant documents.) 

**Expected:** a sequence of one, two, three and four of TALLY MARK ONE should look like the first *n* strokes from TALLY MARK FIVE.

**Actual:** in Noto Sans Symbols 2, the TALLY MARK ONE glyph is centred in a box of the same size as the TALLY MARK FIVE glyph.

**SVG diagram:**

<img src="https://github.com/notofonts/symbols/assets/392868/8d5c3df2-c975-474d-b7e6-4fac4ceef798" alt="Demonstration of the actual and expected renderings of tally marks" width="450" height="262">

**Comment by Mercury13** [comment]
(I suggest making big hangouts, like in tally mark 5, but reducing them with kerning)

**Comment by simoncozens** [comment]
2, 3 and 4 as ligatures. :-) If you do something clever in kerning then the total width of the sequence will be different.

**Comment by chris-morgan** [comment]
That looks like you’re centring one, two and three in the same width as five? If so, that’s definitely wrong: think about how you write tally marks for numbers like six, seven and eight, as shown in my diagram. It needs to be that you’re adding the first, second, third and fourth strokes in the same positions as they are for the five tally.

**Comment by simoncozens** [comment]
Fair. I've gone with 
<img width="549" alt="Screenshot 2024-04-30 at 14 34 52" src="https://github.com/notofonts/symbols/assets/106728/9748d8f5-c9a2-4a39-9fbd-c72ce8823f32">

**Comment by chris-morgan** [comment]
I’m not certain from your picture there, but are you reserving the same width for 1, 2, 3, 4 and 5? If so, I can’t think of any reason for that, and it definitely breaks my expectations. Is there some reason?

**Comment by simoncozens** [comment]
I am, yes. I'm seeing tallies as a kind of tabular numeral.

**Comment by chris-morgan** [comment]
Tabular numerals only make sense for positional numeral systems. I don’t think they make any sense at all for unary numeral systems, which is what tally marks are.

**Comment by chris-morgan** [comment]
Just in case it adds any weight, https://unicode.org/L2/L2015/15328-tally-marks.pdf (the initial proposal wherein 2, 3 and 4 were separately encoded) clearly shows narrow 1, 2 and 3 glyphs:

- in the table on pages 3–4 (the glyphs are centred, but observe the narrow selection box and compare it to U+1D385), and
- in the illustration at the bottom of page 6 (“𝍸𝍸𝍷𝍷𝍷 = 13” obviously lacks any extraneous spacing before the equals sign).

I think I’ve only seen tally marks in one other font, can’t remember what at all, and it wasn’t wide like this either.

**Comment by cyberixae** [comment]
Encountered the same issue. Here is a comparison screenshot with Noto and Catrinity.

<img width="1418" height="443" alt="Image" src="https://github.com/user-attachments/assets/85b23f43-707d-4f98-953c-076c637564a7" />

**Comment by cyberixae** [comment]
The issue seems to be fixed. Can the version number be bumped to make the fix available?
