### ISSUE TITLE
Add missing star rating symbols to Noto Sans Symbols

### ISSUE THREAD

**Issue by agusbou2018** [notofonts/symbols#85]
Please add the following star rating symbols to Noto Sans Symbols:

- Left Half Black Star (⯨, U+2BE8)
- Right Half Black Star (⯩, U+2BE9)
- Star with Left Half Black (⯪, U+2BEA)
- Star with Right Half Black (⯫, U+2BEB)

**Comment by agusbou2018** [comment]
![image](https://github.com/user-attachments/assets/83dbb3b8-ae05-4ea4-930e-5366d3d7df38)

**Comment by mi2ebi** [comment]
they're aware of the characters noto is missing

**Comment by aelatham** [comment]
These are in a different font called Noto Sans Symbols 2. Please close this.
