### ISSUE TITLE
Symbols for Legacy Computing Supplement

### ISSUE THREAD

**Issue by Secret-chest** [notofonts/symbols#86]
**Is your feature request related to a problem? Please describe.**
There's a new Unicode block, and your font having them would help a lot with terminal graphics.

**Describe the solution you'd like**
Add [these characters](https://en.wikipedia.org/wiki/Symbols_for_Legacy_Computing_Supplement)

**Describe alternatives you've considered**
Using another font, but with your font being so widely available it wouldn't make sense.

**Additional context**

**Comment by mi2ebi** [comment]
the designers are already aware of what characters are missing

**Comment by simoncozens** [comment]
Yes, please see the Noto gaplist here: https://notofonts.github.io/overview/gaplist.txt

We'll get to them when we can...
